# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Egor Zakharov
title: Junior Software Engineer
email: Egor.zakharov97@gmail.com
phone: +1 (204) 798-8170

# Social links
github_username: EgorZakharov97
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile_img.jpg
about_content: | # this will include new lines to allow paragraphs
  A fourth-year computer science student with a specialization in software engineering and Computer-Human Interaction.
  Have experience in Machine Learning. Have experienced in full-stack web development.
  Able to apply wide functionalities like user authentication, e-mail chains, the user sessions, Redis Cache, etc.
  Able to develop amd maintein complex database. Have some experience in Android Studio, Amazon Alexa and Tizen Wearable apps.
  I learn fast and always curious about studying new tools.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  Besides software engineering and networks I'm interested in
   - Mountain skiing
   - Sports
   - Fitness

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
